### ISSUE TITLE
Internal Testing Todo

### ISSUE THREAD

**Issue by V4L3NT1N3** [KnightproEx/eatstagram-restaurant#44]
- [ ] Research backend 
- [ ] Unit and integration testing ( post bugs under Issues here )
- [ ] Reorganise code 
- [ ] Requirements gathering ( jumpa boss )
- [ ] Optimise UI/UX , reconsider app flow

**Comment by V4L3NT1N3** [comment]
Everyone can chat and add comments here too
